### ISSUE TITLE
Raamaz da tu verdegniak personaz karismatik..?

### ISSUE THREAD

**Issue by georgesittas** [VasilisOiko/Docker-images#1]
..Ja apoktofiel japropozit aportolu figurneti?

**Comment by VasilisOiko** [comment]
How do you know is me?

**Comment by georgesittas** [comment]
<img width="200" alt="Screenshot 2022-11-11 at 5 19 34 PM" src="https://user-images.githubusercontent.com/46752250/201370375-b3abd9f7-eeeb-462d-b355-1373b788e2a6.png">
